#!/usr/bin/env bash
# fetch-fonts.sh - vendor the dashboard's web fonts into internal/web/fonts/.
#
# The two dashboards used to pull typography from fonts.googleapis.com on every
# page load. That contradicted the rest of the web layer (vendored globe engine,
# vendored vis-network, script-src 'self') and meant an air-gapped or
# egress-filtered deployment rendered in system fallbacks with a CSP that still
# whitelisted two Google hosts. This script downloads the latin subset of each
# family the themes reference, writes them next to the other embedded assets,
# and generates fonts.css with same-origin @font-face rules.
#
# Only the families themes.css actually resolves are fetched:
#   Signal   -> Inter (sans), JetBrains Mono (mono)
#   Meridian -> Barlow (sans + display), IBM Plex Mono (mono)
#   Sprite   -> DM Sans (sans), Pixelify Sans (display); mono is ui-monospace
# Chakra Petch and Space Grotesk were requested by the old <link> tags but no
# theme block ever resolved to them, so they are deliberately not vendored.
#
# Re-run to refresh. Output is deterministic apart from Google's file hashes.
# All six families are licensed under the SIL Open Font License 1.1; see
# internal/web/fonts/README.md.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/internal/web/fonts"
mkdir -p "$OUT"
python3 - "$OUT" <<'PY'
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

out = Path(sys.argv[1])
# A modern Chrome UA makes the CSS API return woff2 + variable fonts and the
# per-script unicode-range subsets; older UAs get TTF and no ranges.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/128.0 Safari/537.36")
families = [
    "Inter:wght@400..700",
    "JetBrains+Mono:wght@400..700",
    "Barlow:wght@400;500;600;700",
    "IBM+Plex+Mono:wght@400;500;600",
    "DM+Sans:opsz,wght@9..40,400..700",
    "Pixelify+Sans:wght@400..700",
]
url = ("https://fonts.googleapis.com/css2?" +
       "&".join("family=" + f for f in families) + "&display=swap")
req = urllib.request.Request(url, headers={"User-Agent": UA})
css = urllib.request.urlopen(req, timeout=30).read().decode("utf-8")

# Blocks look like:  /* latin */\n@font-face { ... src: url(...) ...; unicode-range: ...; }
blocks = re.findall(r"/\* (\w[\w-]*) \*/\s*@font-face\s*\{(.*?)\}", css, re.S)
faces = []
for subset, body in blocks:
    if subset != "latin":
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
    weight = re.search(r"font-weight:\s*([^;]+);", body).group(1).strip()
    style = re.search(r"font-style:\s*([^;]+);", body).group(1).strip()
    src = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
    urange = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()
    slug = fam.lower().replace(" ", "-")
    wslug = "var" if " " in weight else weight
    data = urllib.request.urlopen(
        urllib.request.Request(src, headers={"User-Agent": UA}), timeout=60).read()
    if not data.startswith(b"wOF2"):
        raise SystemExit(f"{src}: not a woff2 file")
    # Content-addressed name: the server marks these immutable for a day, so a
    # re-fetched face must be a NEW url, never new bytes under the old name.
    fname = f"{slug}-{wslug}-{hashlib.sha256(data).hexdigest()[:8]}.woff2"
    faces.append((fam, style, weight, fname, urange, len(data), data))
    print(f"  {fname:40s} {len(data):7d} B  {fam} {weight}")

if not faces:
    raise SystemExit("no latin @font-face blocks found; API response changed?")

# Every download succeeded: replace the directory's faces in one go so a
# failed run never leaves a half-updated set behind.
for old in out.glob("*.woff2"):
    old.unlink()
for _, _, _, fname, _, _, data in faces:
    (out / fname).write_bytes(data)

lines = [
    "/* Generated by scripts/fetch-fonts.sh - do not edit by hand.",
    "   Latin subsets of the families themes.css resolves, served same-origin so",
    "   the dashboards need no egress and the CSP font-src can stay 'self'.",
    "   All faces are SIL OFL 1.1; see README.md in this directory. */",
]
for fam, style, weight, fname, urange, _, _ in faces:
    lines += [
        "@font-face {",
        f"  font-family: '{fam}';",
        f"  font-style: {style};",
        f"  font-weight: {weight};",
        "  font-display: swap;",
        f"  src: url(/fonts/{fname}) format('woff2');",
        f"  unicode-range: {urange};",
        "}",
    ]
(out / "fonts.css").write_text("\n".join(lines) + "\n", encoding="utf-8")
total = sum(f[5] for f in faces)
print(f"wrote {len(faces)} faces ({total} bytes) + fonts.css to {out}")
PY
